pipeline:
  build:
    image: elixir:1.6
    commands:
      - mix local.hex --force
      - mix deps.get
      - mix test
    volumes:
      - ~/.mix
      - _build

matrix:
  ELIXIR_VERSION:
    - 1.4
    - 1.5
    - 1.6
