pipeline:
  build:
    image: elixir:${ELIXIR_VERSION}
    commands:
      - mix local.hex --force
      - mix deps.get
      - mix test
    volumes:
      - /tmp/elixir-dns-.mix:/root/.mix
      - /tmp/elixir-dns-_build:/_build

matrix:
  ELIXIR_VERSION:
    - 1.4
    - 1.5
    - 1.6
