language: elixir

elixir:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - 1.11
otp_release:
  - 19.3
  - 20.3
  - 21.3
  - 22.3
  - 23.1

matrix:
  exclude:
    - elixir: 1.5
      otp_release: 21.0
